# Integration delivery checklist

- [ ] SPI scope: confirm the methods in adapter-spec.json and platform capability registration; do not register unselected methods.
- [ ] Inline field mappings: complete each selected SPI method's anonymous extension in ChannelPaymentService, ChannelRefundService or ChannelNotificationService; document standard/institution fields, requiredness, units, conversion rules and examples. No standalone Mapping classes are required.
- [ ] Security design: document each direction's algorithm, canonical text, encoding, result placement, IV/randomness transfer and rationale for platform or custom computation. Deliver keys separately through the platform's approved secure channel, never in this document.
- [ ] Result-code mappings: institution primary/secondary codes → platform-standard primary/secondary codes. Unknown, processing and failure branches must not default to success.
- [ ] Routing materials: provide production/sandbox domains, path templates and HTTP methods for platform configuration; do not hard-code them in the adapter.
- [ ] Real-SPI delivery cases: complete independently specified scenarios/<method>/<id>.json for every selected method. Include at least one returning success/processing/protocol case per method, plus applicable rejection/input/security/HTTP/mapping failures. Explicitly state context, HTTP and security outcomes, result-code arguments and expected result/exception. Document non-applicable cases; do not derive expectations from the mapper.
- [ ] Platform request context: adapters only read ChannelRequestContext and use its merchantId in security requests. Independent tests simulate bind/finally clear, including missing identity and cleanup after exceptions. runtimeEnv does not replace sandbox routing.
- [ ] Test evidence: pass structure/framework tests, synthetic security-control-flow tests and all real-SPI delivery cases separately. Provide independent algorithm vectors for custom calculation and platform-host conformance evidence for platform calculation. Mocked or synthetic wiring results do not establish institution algorithm compatibility.
- [ ] Test flexibility: completed hooks, private helpers and supported dependencies must not fail skeleton-only assertions. Use setRawBody/getSerializedBody and acceptResponseStatus for confirmed protocol differences; retain platform routing, trusted identity and fail-closed security boundaries. Use ordinary JUnit tests for multi-call protocols or custom exceptions.
- [ ] Dependencies: document each added library's version, purpose and license; the ordinary JAR must not contain the SDK or host runtime.
- [ ] Local reports: include target/ais-delivery/report.json with executed case IDs/categories/hashes, dependency-audit.json, dependency-tree.txt, resolved-dependencies.txt, the ordinary JAR and SHA-256. Obtain human confirmation of scenario completeness and runtime dependencies. The local report explicitly separates platform conformance not executed by ais package.
- [ ] Platform assembly, institution integration testing and release review are complete; local CLI success does not replace these steps.
